- name: cambiar la ruta por defecto
  shell: ip route delete default && ip route add default via {{ip_interna_router}} && echo "post-up route add -net {{ip_interna_local}} netmask {{mascara_larga}} gw {{ip_interna_local}} dev eth1" >> /etc/network/interfaces
